/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlayerDetailsIndexRouteImport } from './routes/player-details/index'
import { Route as OfferComparatorIndexRouteImport } from './routes/offer-comparator/index'
import { Route as ComparatorIndexRouteImport } from './routes/comparator/index'
import { Route as AuctionIndexRouteImport } from './routes/auction/index'
import { Route as PlayerDetailsPlayerIdRouteImport } from './routes/player-details/$playerId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerDetailsIndexRoute = PlayerDetailsIndexRouteImport.update({
  id: '/player-details/',
  path: '/player-details/',
  getParentRoute: () => rootRouteImport,
} as any)
const OfferComparatorIndexRoute = OfferComparatorIndexRouteImport.update({
  id: '/offer-comparator/',
  path: '/offer-comparator/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparatorIndexRoute = ComparatorIndexRouteImport.update({
  id: '/comparator/',
  path: '/comparator/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionIndexRoute = AuctionIndexRouteImport.update({
  id: '/auction/',
  path: '/auction/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayerDetailsPlayerIdRoute = PlayerDetailsPlayerIdRouteImport.update({
  id: '/player-details/$playerId',
  path: '/player-details/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/player-details/$playerId': typeof PlayerDetailsPlayerIdRoute
  '/auction/': typeof AuctionIndexRoute
  '/comparator/': typeof ComparatorIndexRoute
  '/offer-comparator/': typeof OfferComparatorIndexRoute
  '/player-details/': typeof PlayerDetailsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/player-details/$playerId': typeof PlayerDetailsPlayerIdRoute
  '/auction': typeof AuctionIndexRoute
  '/comparator': typeof ComparatorIndexRoute
  '/offer-comparator': typeof OfferComparatorIndexRoute
  '/player-details': typeof PlayerDetailsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/player-details/$playerId': typeof PlayerDetailsPlayerIdRoute
  '/auction/': typeof AuctionIndexRoute
  '/comparator/': typeof ComparatorIndexRoute
  '/offer-comparator/': typeof OfferComparatorIndexRoute
  '/player-details/': typeof PlayerDetailsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/player-details/$playerId'
    | '/auction/'
    | '/comparator/'
    | '/offer-comparator/'
    | '/player-details/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/player-details/$playerId'
    | '/auction'
    | '/comparator'
    | '/offer-comparator'
    | '/player-details'
  id:
    | '__root__'
    | '/'
    | '/player-details/$playerId'
    | '/auction/'
    | '/comparator/'
    | '/offer-comparator/'
    | '/player-details/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlayerDetailsPlayerIdRoute: typeof PlayerDetailsPlayerIdRoute
  AuctionIndexRoute: typeof AuctionIndexRoute
  ComparatorIndexRoute: typeof ComparatorIndexRoute
  OfferComparatorIndexRoute: typeof OfferComparatorIndexRoute
  PlayerDetailsIndexRoute: typeof PlayerDetailsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-details/': {
      id: '/player-details/'
      path: '/player-details'
      fullPath: '/player-details/'
      preLoaderRoute: typeof PlayerDetailsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offer-comparator/': {
      id: '/offer-comparator/'
      path: '/offer-comparator'
      fullPath: '/offer-comparator/'
      preLoaderRoute: typeof OfferComparatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparator/': {
      id: '/comparator/'
      path: '/comparator'
      fullPath: '/comparator/'
      preLoaderRoute: typeof ComparatorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auction/': {
      id: '/auction/'
      path: '/auction'
      fullPath: '/auction/'
      preLoaderRoute: typeof AuctionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/player-details/$playerId': {
      id: '/player-details/$playerId'
      path: '/player-details/$playerId'
      fullPath: '/player-details/$playerId'
      preLoaderRoute: typeof PlayerDetailsPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlayerDetailsPlayerIdRoute: PlayerDetailsPlayerIdRoute,
  AuctionIndexRoute: AuctionIndexRoute,
  ComparatorIndexRoute: ComparatorIndexRoute,
  OfferComparatorIndexRoute: OfferComparatorIndexRoute,
  PlayerDetailsIndexRoute: PlayerDetailsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
